### PR TITLE
Dilpreet branch

### PR DESCRIPTION
**Pull request by DilpreetKaur873**
LogReport Frontend added

LogReport backend added

LogReport styling changed

Routes added

### CODE REVIEW

**Review by doomrt88 — APPROVED** [review]
Everything looks good

**Review by PoojaDayaramani219 — APPROVED** [review]
No conflicts, approved.

**Review by PrinceDholakiya — COMMENTED** [review]
Approved the changed

**Review by PrinceDholakiya — APPROVED** [review]
Approve the changes

**Pull request merged**
